### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by J1angyue** [gxmari007/vite-plugin-eslint#36]
When I add eslint rule: "indent": ["warn", 2] in .eslintrc.json, consoled out below error:
![image](https://user-images.githubusercontent.com/39160902/180442742-e84d153b-e5f2-410c-86bc-b8f8367e9e79.png)
![image](https://user-images.githubusercontent.com/39160902/180442973-19f6633a-b056-49ec-9e5d-0fa872601949.png)

error detail:
[vite] Internal server error: Maximum call stack size exceeded
Occurred while linting D:\Project\use-vben-form\src\components\FormItem\VFormItem.vue:2
Rule: "indent"
  Plugin: vite-plugin-eslint
  File: D:/Project/use-vben-form/src/components/FormItem/VFormItem.vue
      at BinarySearchTree.findLe (D:\Project\use-vben-form\node_modules\.pnpm\registry.npmmirror.com+eslint@8.20.0\node_modules\eslint\lib\rules\indent.js:162:11)
      at OffsetStorage._getOffsetDescriptor (D:\Project\use-vben-form\node_modules\.pnpm\registry.npmmirror.com+eslint@8.20.0\node_modules\eslint\lib\rules\indent.js:262:27)
      at OffsetStorage.getDesiredIndent (D:\Project\use-vben-form\node_modules\.pnpm\registry.npmmirror.com+eslint@8.20.0\node_modules\eslint\lib\rules\indent.js:447:41)
      at OffsetStorage.getDesiredIndent (D:\Project\use-vben-form\node_modules\.pnpm\registry.npmmirror.com+eslint@8.20.0\node_modules\eslint\lib\rules\indent.js:457:45)
      at OffsetStorage.getDesiredIndent (D:\Project\use-vben-form\node_modules\.pnpm\registry.npmmirror.com+eslint@8.20.0\node_modules\eslint\lib\rules\indent.js:457:45)
      at OffsetStorage.getDesiredIndent (D:\Project\use-vben-form\node_modules\.pnpm\registry.npmmirror.com+eslint@8.20.0\node_modules\eslint\lib\rules\indent.js:457:45)
      at OffsetStorage.getDesiredIndent (D:\Project\use-vben-form\node_modules\.pnpm\registry.npmmirror.com+eslint@8.20.0\node_modules\eslint\lib\rules\indent.js:457:45)
      at OffsetStorage.getDesiredIndent (D:\Project\use-vben-form\node_modules\.pnpm\registry.npmmirror.com+eslint@8.20.0\node_modules\eslint\lib\rules\indent.js:457:45)
      at OffsetStorage.getDesiredIndent (D:\Project\use-vben-form\node_modules\.pnpm\registry.npmmirror.com+eslint@8.20.0\node_modules\eslint\lib\rules\indent.js:457:45)
      at OffsetStorage.getDesiredIndent (D:\Project\use-vben-form\node_modules\.pnpm\registry.npmmirror.com+eslint@8.20.0\node_modules\eslint\lib\rules\indent.js:457:45)
Maximum call stack size exceeded
Occurred while linting D:\Project\use-vben-form\src\components\FormItem\VFormItem.vue:2
Rule: "indent"

Steps to Reproduce:
1. Repository: https://github.com/margining/use-vben-form
2. pnpm i
3. pnpm dev
4. open browser url:  http://127.0.0.1:5173
5. wait for a minute, errors come out.

**Comment by J1angyue** [comment]
升级到了最新版（1.8.1）仍提示：Maximum call stack size exceeded。
复现仓库：https://github.com/J1angyue/use-vben-form
![image](https://user-images.githubusercontent.com/39160902/186295204-f385d6d5-ac70-4c74-9740-067805fb61d0.png)

**Comment by gxmari007** [comment]
我复制了你的规则，触发警告，并没有溢出，然而把你的那个组件代码复制过去就崩了😂，感觉是代码问题至于是因为什么没有深入探索。

**Comment by mthaak** [comment]
In my case, the plugin was trying run ESLint on an already built `dist/esm` directory of another local package. So when I disabled that by putting `ignorePatterns: ["dist/*", "node_modules/*"],` in that package's ESLint config, the problem went away. But this might not be a solution for everyone
