### ISSUE TITLE
No ESLint configuration found at 1.8.0

### ISSUE THREAD

**Issue by jiexaspb** [gxmari007/vite-plugin-eslint#38]
After calling npm run build command I get the following error

What can be wrong?
<img width="1250" alt=" — -zsh — 210×48 2022-08-13 01-25-06" src="https://user-images.githubusercontent.com/4509131/184452544-1b893cda-0be2-4949-8673-9bd27c4318ee.png">

The .eslintrc.js configuration file exists and is located at the root of the project

**Comment by gxmari007** [comment]
Can you show me your config?

**Comment by gxmari007** [comment]
Can you show me a demo project?

**Comment by avxit** [comment]
I had the same problem. It's look like new version (`1.8.0`) of the plugin doesn't ignore `node_modules`. The old one (`1.7.0`) works fine.

Here is the log.

```
 ERROR  [commonjs--resolver] Failed to load config "./.config/eslint.config" to extend from.
Referenced from: [PATH_TO_PROJECT]/node_modules/@popperjs/core/package.json
file: [PATH_TO_PROJECT]/node_modules/@popperjs/core/lib/modifiers/arrow.js


 ERROR  error during build:
Error: Failed to load config "./.config/eslint.config" to extend from.
Referenced from: [PATH_TO_PROJECT]/node_modules/@popperjs/core/package.json
    at configInvalidError ([PATH_TO_PROJECT]/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2624:9)
    at ConfigArrayFactory._loadExtendedShareableConfig ([PATH_TO_PROJECT]/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3242:23)
    at ConfigArrayFactory._loadExtends ([PATH_TO_PROJECT]/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3119:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody ([PATH_TO_PROJECT]/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3058:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData ([PATH_TO_PROJECT]/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3003:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory ([PATH_TO_PROJECT]/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2849:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors ([PATH_TO_PROJECT]/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3833:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors ([PATH_TO_PROJECT]/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3852:20)
```

**Comment by alexmccabe** [comment]
Same issue for me for various packages in our project

**Comment by ehsanghorbani190** [comment]
@avxit 
@gxmari007 
I'm still facing the issue.
