### ISSUE TITLE
doesn't work with --moduleResolution bundler

### ISSUE THREAD

**Issue by ianzone** [gxmari007/vite-plugin-eslint#68]
the latest vite `react-swc-ts` template has `"moduleResolution": "bundler"` in tsconfig. it seems the plugin doesn't work with it. 
```
5:33:22 AM [vite] Internal server error:
/home/ian/templates/react/src/main.tsx
  0:0  error  Parsing error: Argument for '--moduleResolution' option must be: 'node', 'classic', 'node16', 'nodenext'

✖ 1 problem (1 error, 0 warnings)

  Plugin: vite-plugin-eslint
  File: /home/ian/templates/react/src/main.tsx
      at formatError (file:///home/ian/templates/react/node_modules/.pnpm/vite@4.0.4_@types+node@18.15.13_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41235:46)
      at TransformContext.error (file:///home/ian/templates/react/node_modules/.pnpm/vite@4.0.4_@types+node@18.15.13_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41231:19)
      at TransformContext.transform (file:///home/ian/templates/react/node_modules/.pnpm/vite-plugin-eslint@1.8.1_eslint@8.31.0_vite@4.0.4/node_modules/vite-plugin-eslint/dist/index.mjs:1:1989)
      at async Object.transform (file:///home/ian/templates/react/node_modules/.pnpm/vite@4.0.4_@types+node@18.15.13_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41506:30)
      at async loadAndTransform (file:///home/ian/templates/react/node_modules/.pnpm/vite@4.0.4_@types+node@18.15.13_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:39313:29) (x2)
```

**Comment by ianzone** [comment]
just figured out my plugin is outdated.
