### ISSUE TITLE
 [vite] Internal server error: Could not find config file.

### ISSUE THREAD

**Issue by XiaofeiCY** [gxmari007/vite-plugin-eslint#93]
when I run dev, I got this error in console log
`Plugin: vite-plugin-eslint
  File: /Users/viteDemo/src/main.ts
      at locateConfigFileToUse (/Users/viteDemo/node_modules/.pnpm/eslint@9.1.1/node_modules/eslint/lib/eslint/eslint.js:350:21)
      at async calculateConfigArray (/Users/viteDemo/node_modules/.pnpm/eslint@9.1.1/node_modules/eslint/lib/eslint/eslint.js:385:49)
      at async ESLint.calculateConfigForFile (/Users/viteDemo/node_modules/.pnpm/eslint@9.1.1/node_modules/eslint/lib/eslint/eslint.js:1176:25)
      at async ESLint.isPathIgnored (/Users/viteDemo/node_modules/.pnpm/eslint@9.1.1/node_modules/eslint/lib/eslint/eslint.js:1200:24)
      at async TransformContext.transform (file:///Users/viteDemo/node_modules/.pnpm/vite-plugin-eslint@1.8.1_eslint@9.1.1_vite@5.2.10/node_modules/vite-plugin-eslint/dist/index.mjs:1:1860)
      at async Object.transform (file:///Users/viteDemo/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:51133:30)
      at async loadAndTransform (file:///Users/viteDemo/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:53888:29)`
 
this is my vite.config.ts

import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'
import eslintPlugin from 'vite-plugin-eslint'
export default defineConfig({
  // plugins: [vue(), vueJsx()],
  plugins: [vue(), vueJsx(), eslintPlugin({ exclude: ['/virtual:/', 'node_modules/**'] })],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  }
})

I don't know how to deal with it, waiting for answer

**Comment by gbourne1** [comment]
Not compatible with eslint@9. I recommend sticking with eslint@8.57.0 until this package is updated. Or can use: https://github.com/ModyQyW/vite-plugin-eslint2

**Comment by XiaofeiCY** [comment]
It actually work! thank you. When I change the eslint verson,I also need to get some other package, such as `eslint-config-airbnb-base`,`eslint-import-resolver-typescript`.but they were all solved.Thank you again!
